name: e2e-tests
on: [push]
jobs: 
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress runs-on
        uses: cypress-io/github-action@v6
        # with: 
        #   start: npm start
      #- uses: actions/upload-artifact@v3
      #  if: failure()
      #  with:
      #    name: cypress-screenshots
      #    path: cypress/screenshots

      #- uses: actions/upload-artifact@v3
      #  if: always()
      #  with:
      #    name: cypress-videos
      #    path: cypress/videos



      # - name: Upload Test Reports
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: newman-test-results
      #     path: newman-report.json




