name: e2e-tests
on: [push]
jobs: 
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress runs-on
        uses: cypress-io/github-action@v6
        with: 
          start: npm start



